spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    kubernetes:
      enabled: true
      discovery:
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver
        all-namespaces: true
        enabled: true

service-1:
  name: user-service
  port: 9000
service-2:
  name: store-service
  port: 9001

server:
  port: 9762
